from enum import Enum


class MediaListSort(Enum):
    MEDIA_ID = 1
    MEDIA_ID_DESC = 2
    SCORE = 3
    SCORE_DESC = 4
    STATUS = 5
    STATUS_DESC = 6
    PROGRESS = 7
    PROGRESS_DESC = 8
    PROGRESS_VOLUMES = 9
    PROGRESS_VOLUMES_DESC = 10
    REPEAT = 11
    REPEAT_DESC = 12
    PRIORITY = 13
    PRIORITY_DESC = 14
    STARTED_ON = 15
    STARTED_ON_DESC = 16
    FINISHED_ON = 17
    FINISHED_ON_DESC = 18
    ADDED_TIME = 19
    ADDED_TIME_DESC = 20
    UPDATED_TIME = 21
    UPDATED_TIME_DESC = 22
    MEDIA_TITLE_ROMAJI = 23
    MEDIA_TITLE_ROMAJI_DESC = 24
    MEDIA_TITLE_ENGLISH = 25
    MEDIA_TITLE_ENGLISH_DESC = 26
    MEDIA_TITLE_NATIVE = 27
    MEDIA_TITLE_NATIVE_DESC = 28
    MEDIA_POPULARITY = 29
    MEDIA_POPULARITY_DESC = 30
