from enum import Enum


class MediaSort(Enum):
    ID = 1
    ID_DESC = 2
    TITLE_ROMAJI = 3
    TITLE_ROMAJI_DESC = 4
    TITLE_ENGLISH = 5
    TITLE_ENGLISH_DESC = 6
    TITLE_NATIVE = 7
    TITLE_NATIVE_DESC = 8
    TYPE = 9
    TYPE_DESC = 10
    FORMAT = 11
    FORMAT_DESC = 12
    START_DATE = 13
    START_DATE_DESC = 14
    END_DATE = 15
    END_DATE_DESC = 16
    SCORE = 17
    SCORE_DESC = 18
    POPULARITY = 19
    POPULARITY_DESC = 20
    TRENDING = 21
    TRENDING_DESC = 22
    EPISODES = 23
    EPISODES_DESC = 24
    DURATION = 25
    DURATION_DESC = 26
    STATUS = 27
    STATUS_DESC = 28
    CHAPTERS = 29
    CHAPTERS_DESC = 30
    VOLUMES = 31
    VOLUMES_DESC = 32
    UPDATED_AT = 33
    UPDATED_AT_DESC = 34
    SEARCH_MATCH = 35
    FAVOURITES = 36
    FAVOURITES_DESC = 37
