from enum import Enum


class CLIState(Enum):
    LOGIN = 1
    ANILIST_MENU = 2
    IN_PROGRESS_DISPLAY = 3
    SEARCH = 4
    TRENDING_MEDIA_DISPLAY = 5
    SEASONAL_MEDIA_DISPLAY = 6
    ALL_TIME_DISPLAY = 7
    UPCOMING_MEDIA_DISPLAY = 8
    MEDIA_INFO_DISPLAY = 9
    MEDIA_INFO_UPDATING = 10
    MEDIA_LIST_DISPLAY = 11
    MEDIA_LIST_UPDATING = 12
